name: rowdy_rehab
description: "This is the Rowdy Rehab app for the UC Athletic Training Department."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  charts_flutter: ^0.12.0
  flutter_bloc: ^8.1.3
  flutter_local_notifications: ^17.0.0
  flutter_staggered_grid_view: ^0.7.0
  image_picker: ^1.0.7
  sqflite: ^2.3.2
  table_calendar: ^3.0.8
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/login_background.png
    - assets/images/Resurgence_Logo.png
  
  fonts:
    - family: Fonttitle
      fonts:
        - asset: fonts/TitleFont.ttf
          weight: 700
